root = "."
tmp_dir = "cmd/api/tmp"

[build]
cmd = "go build -o cmd/api/tmp/main ."
bin = "cmd/api/tmp/main"
full_bin = "cmd/api/tmp/main"
include_ext = ["go"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
